rabbit1:
#  image: relaxart/rabbitmq-server
  build: ./
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "15672:15672"

rabbit2:
#  image: relaxart/rabbitmq-server
  build: ./
  hostname: rabbit2
  links:
    - rabbit1
  environment: 
   - CLUSTER_WITH=rabbit1
   - RAM_NODE=true
  ports:
      - "5673:5672"
      - "15673:15672"

rabbit3:
#  image: relaxart/rabbitmq-server
  build: ./
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment: 
   - CLUSTER_WITH=rabbit1   
  ports:
        - "5674:5672"
        - "15674:15672"
